dist: trusty
language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "6"
  - "7"
  - "node"

before_install:
  - npm install npm@6 -g
  - npm cache verify
  - npm prune
  - npm update

install:
  - npm install

after_install:
  - npm run build

script:
  - npm test
